improve the runit and create_runscript.py scripts
sherimickelson/CM1_benchmarkingWF pull request #10
Opened 2022-03-05 00:29 UTC by sjsprecious

This PR aims at addressing the issue https://github.com/sherimickelson/CM1_benchmarkingWF/issues/8.

The improvements include:

- Add a `machine` variable.
- Use `FC` and `USE_OPENACC` to determine the Fortran compiler and platform and include them in the output log file name.
- Load the environment modules based on the Fortran compiler and machine type (limited to NCAR's machines only).
- Load the consistent modules between `runit` and `create_runscript.py` scripts.
- Fix the queue name issue in the CPU runscript template.

2022-03-06 23:02 UTC, sjsprecious commented
The current framework does not work on Cheyenne as somehow it could not find the MPI library. If I manually specify the MPT library path in the Makefile, the build process is successful but there will be a runtime error related to MPT later.

2022-03-07 15:20 UTC, sherimickelson requested changes
Thanks @sjsprecious for these contributions!  I just had the one very minor suggestion and everything else looks good.

2022-03-07 15:20 UTC, sherimickelson commented on runit
> +cm1_code_base = '/glade/scratch/sunjian/temp/CM1/'
```suggestion
cm1_code_base = '/path/to/CM1/code/base/'
```

2022-03-07 17:30 UTC, sjsprecious commented
Thanks @sherimickelson . Are you able to run this verification framework on Cheyenne?

2022-03-07 23:47 UTC, sherimickelson commented
@sjsprecious I'm not able to run it on cheyenne as well.  I needed to load those modules on the command line and then it was able to get past that error.

2022-03-08 00:10 UTC, sjsprecious commented
> @sjsprecious I'm not able to run it on cheyenne as well. I needed to load those modules on the command line and then it was able to get past that error.

Thanks @sherimickelson . I think we need to load the modules in a different way in the python script (put it in a separate shell script?). IMO, it is inconvenient and likely causing inconsistency to require a user to load the modules manually before running this framework.

2022-03-08 22:43 UTC, sherimickelson approved these changes

2022-03-08 22:43 UTC, merged